// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM77QW7wrCKPfoILTcniIyczrBRgH_BM4',
    appId: '1:26051264337:android:6a50f2a2eb6ed89c035d70',
    messagingSenderId: '26051264337',
    projectId: 'linear-theater-326306',
    storageBucket: 'linear-theater-326306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWyNTFhpdBKPsq5XzSbzTLaVo9wEEr0Q',
    appId: '1:26051264337:ios:a291206ff0674af0035d70',
    messagingSenderId: '26051264337',
    projectId: 'linear-theater-326306',
    storageBucket: 'linear-theater-326306.appspot.com',
    androidClientId: '26051264337-gkonbcp8h5fdidaae383d9d9ah909bd0.apps.googleusercontent.com',
    iosClientId: '26051264337-4g43h60lpttqomg6o29f4kiv172110ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikiProject',
  );
}
